import type { Metadata } from "next";
import { Marcellus, Marcellus_SC, Assistant } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Cursor from "@/components/cursor";

const marcellus = Marcellus({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-marcellus",
});

const marcellusSC = Marcellus_SC({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-marcellus-sc",
});

const assistant = Assistant({
  subsets: ["latin"],
  variable: "--font-assistant",
});

export const metadata: Metadata = {
  title: "Bienvenue Chez Marcel Click & Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        marcellus.variable,
        marcellusSC.variable,
        assistant.variable
      )}
    >
      {/* <Cursor /> */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}